import type { PitchType } from './types';

/**
 * Every pitch in the game.
 *
 * Stats here are for a league-average version of the pitch; a created pitcher's
 * ratings and per-pitch grade scale them up or down (see player.ts). The tunnel
 * groups drive deception: the whole 'hard' family — fastballs and every
 * fastball-disguised offspeed pitch — leaves the hand on the same look, which
 * is why a splitter lives and dies by the heaters thrown before it.
 */
export const PITCH_CATALOG: PitchType[] = [
  // ---- fastballs -----------------------------------------------------------
  {
    id: 'FF',
    name: 'Four-Seam',
    abbrev: 'FF',
    velo: 96,
    break: { x: 0.1, y: 0.55 },
    controlDifficulty: 0.18,
    accuracyWindow: 0.13,
    whiff: 0.4,
    chase: 0.28,
    gb: 0.28,
    tunnel: 'hard',
    speedClass: 'hard',
    color: '#e8503a',
    blurb: 'Rides up. Beats hitters at the top of the zone, gets crushed at the belt.',
  },
  {
    id: 'FT',
    name: 'Two-Seam',
    abbrev: 'FT',
    velo: 95,
    break: { x: -0.55, y: -0.1 },
    controlDifficulty: 0.22,
    accuracyWindow: 0.12,
    whiff: 0.28,
    chase: 0.31,
    gb: 0.58,
    tunnel: 'hard',
    speedClass: 'hard',
    color: '#e06a4a',
    blurb: 'Fastball with arm-side run. Steals called strikes back over the corner.',
  },
  {
    id: 'SI',
    name: 'Sinker',
    abbrev: 'SI',
    velo: 94,
    break: { x: -0.75, y: -0.45 },
    controlDifficulty: 0.26,
    accuracyWindow: 0.12,
    whiff: 0.26,
    chase: 0.33,
    gb: 0.78,
    tunnel: 'hard',
    speedClass: 'hard',
    color: '#e0873c',
    blurb: 'Arm-side run, down. Not a bat-misser — a double-play pitch.',
  },
  {
    id: 'FC',
    name: 'Cutter',
    abbrev: 'FC',
    velo: 91,
    break: { x: 0.5, y: -0.1 },
    controlDifficulty: 0.28,
    accuracyWindow: 0.115,
    whiff: 0.38,
    chase: 0.38,
    gb: 0.45,
    tunnel: 'hard',
    speedClass: 'hard',
    color: '#d4b23c',
    blurb: 'A fastball that isn’t, by three inches. Saws off barrels in on the hands.',
  },
  // ---- breaking balls ------------------------------------------------------
  {
    id: 'SL',
    name: 'Slider',
    abbrev: 'SL',
    velo: 87,
    break: { x: 0.95, y: -0.6 },
    controlDifficulty: 0.36,
    accuracyWindow: 0.1,
    whiff: 0.6,
    chase: 0.66,
    gb: 0.52,
    tunnel: 'sweep',
    speedClass: 'breaking',
    color: '#3f8ee0',
    blurb: 'Glove-side sweep. Your put-away pitch off the plate with two strikes.',
  },
  {
    id: 'ST',
    name: 'Sweeper',
    abbrev: 'ST',
    velo: 84,
    break: { x: 1.5, y: -0.3 },
    controlDifficulty: 0.4,
    accuracyWindow: 0.095,
    whiff: 0.58,
    chase: 0.6,
    gb: 0.4,
    tunnel: 'sweep',
    speedClass: 'breaking',
    color: '#4fa3d4',
    blurb: 'A slider that keeps going. Huge horizontal break, murder on same-side hitters.',
  },
  {
    id: 'SV',
    name: 'Slurve',
    abbrev: 'SV',
    velo: 82,
    break: { x: 1.15, y: -0.95 },
    controlDifficulty: 0.42,
    accuracyWindow: 0.09,
    whiff: 0.54,
    chase: 0.52,
    gb: 0.5,
    tunnel: 'sweep',
    speedClass: 'breaking',
    color: '#5f8ed6',
    blurb: 'Two-plane break, neither committed. Harder to read than either parent.',
  },
  {
    id: 'CB',
    name: 'Curveball',
    abbrev: 'CB',
    velo: 80,
    break: { x: 0.45, y: -1.45 },
    controlDifficulty: 0.5,
    accuracyWindow: 0.085,
    whiff: 0.55,
    chase: 0.46,
    gb: 0.6,
    tunnel: 'loop',
    speedClass: 'breaking',
    color: '#9b6fd4',
    blurb: 'Huge depth, hardest to command. A hung curve is the worst pitch in baseball.',
  },
  {
    id: 'KC',
    name: 'Knuckle-Curve',
    abbrev: 'KC',
    velo: 82,
    break: { x: 0.55, y: -1.3 },
    controlDifficulty: 0.48,
    accuracyWindow: 0.085,
    whiff: 0.58,
    chase: 0.5,
    gb: 0.58,
    tunnel: 'loop',
    speedClass: 'breaking',
    color: '#8a7ad9',
    blurb: 'A curve with harder spike and later bite. Trades a little depth for deception.',
  },
  {
    id: 'SC',
    name: 'Screwball',
    abbrev: 'SC',
    velo: 81,
    break: { x: -1.1, y: -0.75 },
    controlDifficulty: 0.5,
    accuracyWindow: 0.085,
    whiff: 0.5,
    chase: 0.52,
    gb: 0.55,
    tunnel: 'loop',
    speedClass: 'breaking',
    color: '#b06fc4',
    blurb: 'Breaks the wrong way. Nobody throws it, which is exactly why it works.',
  },
  {
    id: 'EP',
    name: 'Eephus',
    abbrev: 'EP',
    velo: 64,
    break: { x: 0.1, y: -1.8 },
    controlDifficulty: 0.45,
    accuracyWindow: 0.08,
    whiff: 0.3,
    chase: 0.22,
    gb: 0.32,
    tunnel: 'loop',
    speedClass: 'breaking',
    color: '#c9a0e8',
    blurb: 'A 64 mph insult. Pure timing destruction — use once a game, maybe.',
  },
  // ---- offspeed (all disguised as fastballs) -------------------------------
  {
    id: 'CH',
    name: 'Changeup',
    abbrev: 'CH',
    velo: 85,
    break: { x: -0.8, y: -0.75 },
    controlDifficulty: 0.38,
    accuracyWindow: 0.1,
    whiff: 0.54,
    chase: 0.62,
    gb: 0.62,
    tunnel: 'hard',
    speedClass: 'offspeed',
    color: '#4fb477',
    blurb: 'Fastball out of the hand, 11 mph slower. Only as good as the fastballs before it.',
  },
  {
    id: 'CC',
    name: 'Circle Change',
    abbrev: 'CC',
    velo: 83,
    break: { x: -1.1, y: -0.6 },
    controlDifficulty: 0.4,
    accuracyWindow: 0.095,
    whiff: 0.5,
    chase: 0.6,
    gb: 0.66,
    tunnel: 'hard',
    speedClass: 'offspeed',
    color: '#45c48a',
    blurb: 'A changeup that fades like a screwball. Runs off the plate away from opposite hands.',
  },
  {
    id: 'FS',
    name: 'Splitter',
    abbrev: 'FS',
    velo: 88,
    break: { x: -0.3, y: -1.15 },
    controlDifficulty: 0.44,
    accuracyWindow: 0.09,
    whiff: 0.66,
    chase: 0.6,
    gb: 0.7,
    tunnel: 'hard',
    speedClass: 'offspeed',
    color: '#3cb8a8',
    blurb: 'Fastball that falls off a table at the plate. The best swing-and-miss pitch alive.',
  },
  {
    id: 'FO',
    name: 'Forkball',
    abbrev: 'FO',
    velo: 84,
    break: { x: -0.2, y: -1.3 },
    controlDifficulty: 0.48,
    accuracyWindow: 0.085,
    whiff: 0.6,
    chase: 0.55,
    gb: 0.68,
    tunnel: 'hard',
    speedClass: 'offspeed',
    color: '#38a89a',
    blurb: 'The splitter’s older, meaner cousin. Deeper drop, harder on the arm and the aim.',
  },
  {
    id: 'VC',
    name: 'Vulcan Change',
    abbrev: 'VC',
    velo: 83,
    break: { x: -0.7, y: -0.95 },
    controlDifficulty: 0.42,
    accuracyWindow: 0.09,
    whiff: 0.52,
    chase: 0.58,
    gb: 0.66,
    tunnel: 'hard',
    speedClass: 'offspeed',
    color: '#52bd9e',
    blurb: 'Split-fingered changeup with tumble. Splits the difference between change and splitter.',
  },
  {
    id: 'PB',
    name: 'Palmball',
    abbrev: 'PB',
    velo: 79,
    break: { x: -0.5, y: -0.9 },
    controlDifficulty: 0.46,
    accuracyWindow: 0.085,
    whiff: 0.42,
    chase: 0.48,
    gb: 0.6,
    tunnel: 'hard',
    speedClass: 'offspeed',
    color: '#6abf8e',
    blurb: 'Dead fish out of the palm. An old-timer’s pitch that still gets old-timer outs.',
  },
  // ---- the outlier ---------------------------------------------------------
  {
    id: 'KN',
    name: 'Knuckleball',
    abbrev: 'KN',
    velo: 76,
    break: { x: 0, y: -0.6 },
    controlDifficulty: 0.55,
    accuracyWindow: 0.08,
    whiff: 0.5,
    chase: 0.35,
    gb: 0.45,
    tunnel: 'flutter',
    speedClass: 'offspeed',
    flutter: true,
    color: '#c4b06f',
    blurb: 'Nobody knows where it’s going — including you. Re-rolls its break every throw.',
  },
];

export const CATALOG_BY_ID: Record<string, PitchType> = Object.fromEntries(
  PITCH_CATALOG.map((p) => [p.id, p]),
);

export function getCatalogPitch(id: string): PitchType {
  const p = CATALOG_BY_ID[id];
  if (!p) throw new Error(`Unknown pitch: ${id}`);
  return p;
}
